import { Injectable, signal } from '@angular/core';
import { Product } from '../types/product.interface';

@Injectable({ providedIn: 'root' })
export class ProductsData {
  private readonly _products = signal<Product[]>([
    {
      id: 'p1',
      name: 'AuraBook Pro 14"',
      description: 'Ultra-thin laptop with a neural engine and a liquid retina display.',
      price: 999,
      originalPrice: 1299,
      image: 'https://picsum.photos/seed/aurabook/600/450',
      category: 'laptops',
      color: 'silver',
      inStock: true,
      discount: 23,
    },
    {
      id: 'p2',
      name: 'Nexus Studio Workstation',
      description: 'Desktop tower built for heavy AI workloads and 3D rendering.',
      price: 2499,
      image: 'https://picsum.photos/seed/nexus/600/450',
      category: 'laptops',
      color: 'black',
      badge: 'Best Seller',
      inStock: true,
    },
    {
      id: 'p3',
      name: 'ClarityVision 27" 4K',
      description: 'Color-accurate professional monitor with USB-C hub connectivity.',
      price: 599,
      image: 'https://picsum.photos/seed/clarity/600/450',
      category: 'laptops',
      color: 'white',
      inStock: false,
    },
    {
      id: 'p4',
      name: 'ErgoPro Mechanical Keyboard',
      description: 'Tactile split keyboard designed for long coding sessions.',
      price: 99,
      originalPrice: 149,
      image: 'https://picsum.photos/seed/ergopro/600/450',
      category: 'laptops',
      color: 'black',
      inStock: true,
      discount: 34,
    },
    {
      id: 'p5',
      name: 'Pulse Wireless Earbuds',
      description: 'Active noise cancelling earbuds with a 30-hour battery case.',
      price: 179,
      image: 'https://picsum.photos/seed/pulse/600/450',
      category: 'audio',
      color: 'white',
      badge: 'Best Seller',
      inStock: true,
    },
    {
      id: 'p6',
      name: 'Orbit Smartwatch Series 4',
      description: 'Health tracking, cellular connectivity, always-on display.',
      price: 399,
      image: 'https://picsum.photos/seed/orbit/600/450',
      category: 'wearables',
      color: 'blue',
      badge: 'New',
      inStock: true,
    },
    {
      id: 'p7',
      name: 'Fusion 15 Gaming Laptop',
      description: 'High refresh rate display with dedicated ray-tracing GPU.',
      price: 1899,
      image: 'https://picsum.photos/seed/fusion/600/450',
      category: 'laptops',
      color: 'black',
      inStock: false,
    },
    {
      id: 'p8',
      name: 'Halo Pro Smartphone',
      description: 'Flagship camera system with all-day battery life.',
      price: 799,
      originalPrice: 999,
      image: 'https://picsum.photos/seed/halo/600/450',
      category: 'smartphones',
      color: 'blue',
      inStock: true,
      discount: 20,
    },
    {
      id: 'p9',
      name: 'DriftBand Fitness Tracker',
      description: 'Lightweight tracker with sleep analysis and GPS.',
      price: 89,
      image: 'https://picsum.photos/seed/drift/600/450',
      category: 'wearables',
      color: 'red',
      inStock: true,
    },
    {
      id: 'p10',
      name: 'SoundWave Speaker',
      description: '360° room-filling sound with deep bass and crisp highs.',
      price: 129,
      originalPrice: 179,
      image: 'https://picsum.photos/seed/soundwave/600/450',
      category: 'audio',
      color: 'black',
      inStock: true,
      discount: 28,
    },
    {
      id: 'p11',
      name: 'Nova Smartphone X',
      description: 'Edge-to-edge AMOLED display with 200MP camera system.',
      price: 1099,
      image: 'https://picsum.photos/seed/nova/600/450',
      category: 'smartphones',
      color: 'silver',
      badge: 'New',
      inStock: true,
    },
    {
      id: 'p12',
      name: 'AirZone True Wireless',
      description: 'Crystal clear calls with adaptive noise cancellation.',
      price: 79,
      image: 'https://picsum.photos/seed/airzone/600/450',
      category: 'audio',
      color: 'white',
      inStock: false,
    },
    {
      id: 'p13',
      name: 'PeakRun GPS Watch',
      description: 'Advanced running metrics with heart rate and VO2 max.',
      price: 249,
      image: 'https://picsum.photos/seed/peakrun/600/450',
      category: 'wearables',
      color: 'red',
      inStock: true,
    },
    {
      id: 'p14',
      name: 'SlimPhone Air',
      description: 'The thinnest smartphone ever made, 5.4mm profile.',
      price: 649,
      originalPrice: 849,
      image: 'https://picsum.photos/seed/slimphone/600/450',
      category: 'smartphones',
      color: 'silver',
      inStock: true,
      discount: 24,
    },
    {
      id: 'p15',
      name: 'StudioMix Headphones',
      description: 'Professional-grade studio headphones with flat frequency response.',
      price: 299,
      image: 'https://picsum.photos/seed/studiomix/600/450',
      category: 'audio',
      color: 'black',
      badge: 'Best Seller',
      inStock: true,
    },
    {
      id: 'p16',
      name: 'VisionTab Pro',
      description: '12.9" tablet with M3 chip and mini-LED display.',
      price: 1199,
      image: 'https://picsum.photos/seed/visiontab/600/450',
      category: 'laptops',
      color: 'silver',
      inStock: true,
    },
    {
      id: 'p17',
      name: 'GlowBand Smart Ring',
      description: 'Discreet health tracker in a stylish ring form factor.',
      price: 199,
      image: 'https://picsum.photos/seed/glowband/600/450',
      category: 'wearables',
      color: 'silver',
      badge: 'New',
      inStock: true,
    },
    {
      id: 'p18',
      name: 'ZenPhone Lite',
      description: 'Long battery life smartphone for everyday essentials.',
      price: 349,
      image: 'https://picsum.photos/seed/zenphone/600/450',
      category: 'smartphones',
      color: 'blue',
      inStock: false,
    },
  ]);

  readonly products = this._products.asReadonly();
}
