import type { HlmStyle } from './hlm-style';

export const navMenuClasses: Record<HlmStyle, string> = {
  nova: 'gap-1 flex data-[orientation=vertical]:flex-col data-[orientation=horizontal]:flex-row',
  vega: 'gap-1 flex data-[orientation=vertical]:flex-col data-[orientation=horizontal]:flex-row',
  lyra: 'gap-1 flex data-[orientation=vertical]:flex-col data-[orientation=horizontal]:flex-row',
  maia: 'gap-1 flex data-[orientation=vertical]:flex-col data-[orientation=horizontal]:flex-row',
  mira: 'gap-1 flex data-[orientation=vertical]:flex-col data-[orientation=horizontal]:flex-row',
  luma: 'gap-1 flex data-[orientation=vertical]:flex-col data-[orientation=horizontal]:flex-row',
};

export const navMenuTriggerClasses: Record<HlmStyle, string> = {
  nova: 'group/nav-trigger flex h-8 w-max items-center justify-center gap-1.5 rounded-lg px-2.5 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  vega: 'group/nav-trigger flex h-9 w-max items-center justify-center gap-1.5 rounded-md px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  lyra: 'group/nav-trigger flex h-8 w-max items-center justify-center gap-1.5 rounded-none px-2.5 text-xs font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  maia: 'group/nav-trigger flex h-9 w-max items-center justify-center gap-1.5 rounded-2xl px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  mira: 'group/nav-trigger flex h-7 w-max items-center justify-center gap-1 rounded-md px-2 text-xs/relaxed font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  luma: 'group/nav-trigger flex h-9 w-max items-center justify-center gap-1.5 rounded-3xl px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
};

export const navMenuContentClasses: Record<HlmStyle, string> = {
  nova: 'data-[motion^=from-]:animate-in data-[motion^=to-]:animate-out data-[motion^=from-]:fade-in data-[motion^=to-]:fade-out top-0 left-0 w-full p-2 pr-2.5 md:w-auto data-[orientation=horizontal]:data-[motion=from-end]:slide-in-from-right-52 data-[orientation=horizontal]:data-[motion=from-start]:slide-in-from-left-52 data-[orientation=horizontal]:data-[motion=to-end]:slide-out-to-right-52 data-[orientation=horizontal]:data-[motion=to-start]:slide-out-to-left-52 data-[orientation=vertical]:data-[motion=from-end]:slide-in-from-bottom-52 data-[orientation=vertical]:data-[motion=from-start]:slide-in-from-top-52 data-[orientation=vertical]:data-[motion=to-end]:slide-out-to-bottom-52 data-[orientation=vertical]:data-[motion=to-start]:slide-out-to-top-52 data-[orientation=horizontal]:mt-[--spacing(var(--nav-offset))] data-[orientation=vertical]:mx-[--spacing(var(--nav-offset))] bg-popover text-popover-foreground ring-foreground/10 rounded-lg shadow ring-1 transition-all ease-[cubic-bezier(0.22,1,0.36,1)] outline-none data-ending-style:scale-90 data-ending-style:opacity-0 data-ending-style:duration-150 data-starting-style:scale-90 data-starting-style:opacity-0 block',
  vega: 'data-[motion^=from-]:animate-in data-[motion^=to-]:animate-out data-[motion^=from-]:fade-in data-[motion^=to-]:fade-out top-0 left-0 w-full p-2 pr-2.5 md:w-auto data-[orientation=horizontal]:data-[motion=from-end]:slide-in-from-right-52 data-[orientation=horizontal]:data-[motion=from-start]:slide-in-from-left-52 data-[orientation=horizontal]:data-[motion=to-end]:slide-out-to-right-52 data-[orientation=horizontal]:data-[motion=to-start]:slide-out-to-left-52 data-[orientation=vertical]:data-[motion=from-end]:slide-in-from-bottom-52 data-[orientation=vertical]:data-[motion=from-start]:slide-in-from-top-52 data-[orientation=vertical]:data-[motion=to-end]:slide-out-to-bottom-52 data-[orientation=vertical]:data-[motion=to-start]:slide-out-to-top-52 data-[orientation=horizontal]:mt-[--spacing(var(--nav-offset))] data-[orientation=vertical]:mx-[--spacing(var(--nav-offset))] bg-popover text-popover-foreground ring-foreground/10 rounded-lg shadow ring-1 transition-all ease-[cubic-bezier(0.22,1,0.36,1)] outline-none data-ending-style:scale-90 data-ending-style:opacity-0 data-ending-style:duration-150 data-starting-style:scale-90 data-starting-style:opacity-0 block',
  lyra: 'data-[motion^=from-]:animate-in data-[motion^=to-]:animate-out data-[motion^=from-]:fade-in data-[motion^=to-]:fade-out top-0 left-0 w-full p-2 pr-2.5 md:w-auto data-[orientation=horizontal]:data-[motion=from-end]:slide-in-from-right-52 data-[orientation=horizontal]:data-[motion=from-start]:slide-in-from-left-52 data-[orientation=horizontal]:data-[motion=to-end]:slide-out-to-right-52 data-[orientation=horizontal]:data-[motion=to-start]:slide-out-to-left-52 data-[orientation=vertical]:data-[motion=from-end]:slide-in-from-bottom-52 data-[orientation=vertical]:data-[motion=from-start]:slide-in-from-top-52 data-[orientation=vertical]:data-[motion=to-end]:slide-out-to-bottom-52 data-[orientation=vertical]:data-[motion=to-start]:slide-out-to-top-52 data-[orientation=horizontal]:mt-[--spacing(var(--nav-offset))] data-[orientation=vertical]:mx-[--spacing(var(--nav-offset))] bg-popover text-popover-foreground ring-foreground/10 rounded-none shadow ring-1 transition-all ease-[cubic-bezier(0.22,1,0.36,1)] outline-none data-ending-style:scale-90 data-ending-style:opacity-0 data-ending-style:duration-150 data-starting-style:scale-90 data-starting-style:opacity-0 block',
  maia: 'data-[motion^=from-]:animate-in data-[motion^=to-]:animate-out data-[motion^=from-]:fade-in data-[motion^=to-]:fade-out top-0 left-0 w-full p-2 pr-2.5 md:w-auto data-[orientation=horizontal]:data-[motion=from-end]:slide-in-from-right-52 data-[orientation=horizontal]:data-[motion=from-start]:slide-in-from-left-52 data-[orientation=horizontal]:data-[motion=to-end]:slide-out-to-right-52 data-[orientation=horizontal]:data-[motion=to-start]:slide-out-to-left-52 data-[orientation=vertical]:data-[motion=from-end]:slide-in-from-bottom-52 data-[orientation=vertical]:data-[motion=from-start]:slide-in-from-top-52 data-[orientation=vertical]:data-[motion=to-end]:slide-out-to-bottom-52 data-[orientation=vertical]:data-[motion=to-start]:slide-out-to-top-52 data-[orientation=horizontal]:mt-[--spacing(var(--nav-offset))] data-[orientation=vertical]:mx-[--spacing(var(--nav-offset))] bg-popover text-popover-foreground ring-foreground/5 rounded-2xl shadow ring-1 transition-all ease-[cubic-bezier(0.22,1,0.36,1)] outline-none data-ending-style:scale-90 data-ending-style:opacity-0 data-ending-style:duration-150 data-starting-style:scale-90 data-starting-style:opacity-0 block',
  mira: 'data-[motion^=from-]:animate-in data-[motion^=to-]:animate-out data-[motion^=from-]:fade-in data-[motion^=to-]:fade-out top-0 left-0 w-full p-2 pr-2.5 md:w-auto data-[orientation=horizontal]:data-[motion=from-end]:slide-in-from-right-52 data-[orientation=horizontal]:data-[motion=from-start]:slide-in-from-left-52 data-[orientation=horizontal]:data-[motion=to-end]:slide-out-to-right-52 data-[orientation=horizontal]:data-[motion=to-start]:slide-out-to-left-52 data-[orientation=vertical]:data-[motion=from-end]:slide-in-from-bottom-52 data-[orientation=vertical]:data-[motion=from-start]:slide-in-from-top-52 data-[orientation=vertical]:data-[motion=to-end]:slide-out-to-bottom-52 data-[orientation=vertical]:data-[motion=to-start]:slide-out-to-top-52 data-[orientation=horizontal]:mt-[--spacing(var(--nav-offset))] data-[orientation=vertical]:mx-[--spacing(var(--nav-offset))] bg-popover text-popover-foreground ring-foreground/10 rounded-xl shadow ring-1 transition-all ease-[cubic-bezier(0.22,1,0.36,1)] outline-none data-ending-style:scale-90 data-ending-style:opacity-0 data-ending-style:duration-150 data-starting-style:scale-90 data-starting-style:opacity-0 block',
  luma: 'data-[motion^=from-]:animate-in data-[motion^=to-]:animate-out data-[motion^=from-]:fade-in data-[motion^=to-]:fade-out top-0 left-0 w-full p-2 pr-2.5 md:w-auto data-[orientation=horizontal]:data-[motion=from-end]:slide-in-from-right-52 data-[orientation=horizontal]:data-[motion=from-start]:slide-in-from-left-52 data-[orientation=horizontal]:data-[motion=to-end]:slide-out-to-right-52 data-[orientation=horizontal]:data-[motion=to-start]:slide-out-to-left-52 data-[orientation=vertical]:data-[motion=from-end]:slide-in-from-bottom-52 data-[orientation=vertical]:data-[motion=from-start]:slide-in-from-top-52 data-[orientation=vertical]:data-[motion=to-end]:slide-out-to-bottom-52 data-[orientation=vertical]:data-[motion=to-start]:slide-out-to-top-52 data-[orientation=horizontal]:mt-[--spacing(var(--nav-offset))] data-[orientation=vertical]:mx-[--spacing(var(--nav-offset))] bg-popover text-popover-foreground ring-foreground/5 dark:ring-foreground/10 rounded-3xl shadow-lg ring-1 transition-all ease-[cubic-bezier(0.22,1,0.36,1)] outline-none data-ending-style:scale-90 data-ending-style:opacity-0 data-ending-style:duration-150 data-starting-style:scale-90 data-starting-style:opacity-0 block',
};

export const navMenuItemClasses: Record<HlmStyle, string> = {
  nova: 'group/nav-item relative flex h-8 w-max items-center justify-center gap-1.5 rounded-lg px-2.5 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  vega: 'group/nav-item relative flex h-9 w-max items-center justify-center gap-1.5 rounded-md px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  lyra: 'group/nav-item relative flex h-8 w-max items-center justify-center gap-1.5 rounded-none px-2.5 text-xs font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  maia: 'group/nav-item relative flex h-9 w-max items-center justify-center gap-1.5 rounded-2xl px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  mira: 'group/nav-item relative flex h-7 w-max items-center justify-center gap-1 rounded-md px-2 text-xs/relaxed font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  luma: 'group/nav-item relative flex h-9 w-max items-center justify-center gap-1.5 rounded-3xl px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 data-[state=open]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
};

export const navMenuLinkClasses: Record<HlmStyle, string> = {
  nova: 'flex h-8 w-max items-center justify-center gap-1.5 rounded-lg px-2.5 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  vega: 'flex h-9 w-max items-center justify-center gap-1.5 rounded-md px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  lyra: 'flex h-8 w-max items-center justify-center gap-1.5 rounded-none px-2.5 text-xs font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  maia: 'flex h-9 w-max items-center justify-center gap-1.5 rounded-2xl px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  mira: 'flex h-7 w-max items-center justify-center gap-1 rounded-md px-2 text-xs/relaxed font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
  luma: 'flex h-9 w-max items-center justify-center gap-1.5 rounded-3xl px-3 text-sm font-medium outline-none transition-colors select-none data-[active=true]:bg-muted/50 hover:bg-muted/50 disabled:pointer-events-none disabled:opacity-50 [&>ng-icon]:text-[length:--spacing(4)] [&>ng-icon]:shrink-0',
};

export const navMenuListClasses: Record<HlmStyle, string> = {
  nova: 'group/nav-list flex flex-1 list-none items-center justify-center gap-1 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-0',
  vega: 'group/nav-list flex flex-1 list-none items-center justify-center gap-1 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-0',
  lyra: 'group/nav-list flex flex-1 list-none items-center justify-center gap-1 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-0',
  maia: 'group/nav-list flex flex-1 list-none items-center justify-center gap-1 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-0',
  mira: 'group/nav-list flex flex-1 list-none items-center justify-center gap-1 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-0',
  luma: 'group/nav-list flex flex-1 list-none items-center justify-center gap-1 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-0',
};
